# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
  configuration: debug
  platform: x64

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'
 
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'android/gradlew'
    workingDirectory: 'android'
    tasks: 'clean'
    javaHomeOption: 'JDKVersion'
  displayName: "Clean gradlew"
  
- task: Gradle@2
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    tasks: 'assembleRelease'
    javaHomeOption: 'JDKVersion'
  continueOnError: false
  displayName: "Compile apk assemblerelease"
  

- script: ls android/app/build/outputs/apk/release
  displayName: Android Postprocess
  continueOnError: false

